# Generated by Django 3.0.3 on 2020-06-04 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0010_auto_20200604_1725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='author',
            new_name='user',
        ),
    ]
