# Generated by Django 3.0.3 on 2020-06-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0003_post_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likedUsers',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='post',
            name='numLikes',
            field=models.IntegerField(default=0),
        ),
    ]
