# Generated by Django 3.0.3 on 2020-06-08 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0006_auto_20200603_0126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
